### PR TITLE
Some more slashcommands

### PR DESCRIPTION
**Pull request by wiiaboo**
Can never have too many of them.

### CODE REVIEW

**Comment by wiiaboo** [comment]
Hm, can't create a new page from inject.js to a `view-source` URL, has to be from background.js. Some idea on how to do this, @arnoudkooi?

**Comment by arnoudkooi** [comment]
Thanks, I have some in flight changes, so need to see if I can do the pull on this one.. Have a look at `snutils-event` in the sourcecode to see the event dispatching

**Comment by wiiaboo** [comment]
@arnoudkooi thanks, that simplified things a bit.

**Comment by arnoudkooi** [comment]
Due to changes in the structure, i have just coomy I will apply the suggested changes in another commit, and close this PR. Thanks!

**Comment by arnoudkooi** [comment]
Added in v 3.7 in other commit
https://github.com/arnoudkooi/ServiceNow-Utils/commit/7418fcc7d17a912b3fe9384407497a07a86005bb

**Pull request closed without merging**
