### PR TITLE
Small fixes and undeprecation to allow extension in Firefox

### PR DESCRIPTION
**Pull request by wiiaboo**
There were very few things needed to make this work in Firefox, luckily.

I took the time to fix a small nagging issue where you couldn't focus the search inputs if focused inside the iframe.

If some Firefox user wants to try it, I can try to fix any Firefox-only issues.

[servicenow_utils-2.7.2-an+fx.zip](https://github.com/arnoudkooi/ServiceNow-Utils/files/2475675/servicenow_utils-2.7.2-an%2Bfx.zip)
This was built with [web-ext](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext) with plain `web-ext sign` on the repo root as is of e2a350b and signed with my AMO API key so it could be installed into non-developer browsers.

### CODE REVIEW

**Comment by arnoudkooi** [comment]
Is this still compatible with the Chrome version?

**Comment by wiiaboo** [comment]
The only thing that might be broken could be the ScriptSyncer, but that might be because my unloaded extension might not be trusted by it. Only you can test that, I think.

At most, there will be an error with the manifest since Chrome doesn't like 'applications', just as Firefox doesn't like 'permissions.declarativeContent' and 'background.persistent'. The usual solution is to make two manifests and switch between them when packaging for either browser.

**Comment by wiiaboo** [comment]
Yeah, I had to change the extension id on both the scriptsyncer and on servicenow-utils, but it worked fine.

**Comment by wiiaboo** [comment]
Any news on merging this and publishing to AMO?
There's a few Firefox fans here waiting for that (me included, I've using a dev build daily).

**Comment by arnoudkooi** [comment]
Will try to find time this weekend

**Comment by wiiaboo** [comment]
I can check into it. That's the result of a manual review. With private signed build I only got an automatized review, so I didn't get as many such issues.

**Comment by wiiaboo** [comment]
Unless I've read it wrong, they just want you to make sure you're using the latest possible versions of the 3rd party libraries and make sure there are no custom modifications to them, not that you have to load them using a CDN (since that's not even feasible for background scripts).

I've started updating some yesterday, but I'm having trouble with font-awesome, since there's been big changes to 5.x.

If you know best where you got your scripts from, it might be better you do this yourself. And removing scripts/resources that are not being used.

**Pull request merged**
