### PR TITLE
Zv/scope search by group

### PR DESCRIPTION
**Pull request by gitZoranVasic**
**Commits**
Scoped search by Search Group
Added checkbox for including default tables
Added description of the group

**Description:**
As a user you can select which search group you want to search and choose weather to include default tables. So you can have scoped search by creating new search group and adding tables you want searched. There is a link for Search Group Table for easier creation of the new tables and description is shown below the select. 

**Screenshot:**
image

### CODE REVIEW

**Comment by arnoudkooi** [comment]
Will test this in next days, thanks so far

**Comment by gitZoranVasic** [comment]
Yeah sure, thank you :)

If you like what I did with this, I have another feature I could implement, quick collapse and uncollapse.

**Comment by arnoudkooi** [comment]
I have the default tables in, to give a priority in order i.e. search script includes first, searching a table that is not in the group will not work probably...

**Comment by gitZoranVasic** [comment]
It does actually, see the images, the .wow Search Group is set only to have sp_widget table in it, but it searches for all default tables.

image

**Comment by arnoudkooi** [comment]
Ok, if its not the default group I want to hide the list of suggestions at the bottom. That collapse idea seems good as well.

**Comment by gitZoranVasic** [comment]
Sure, I wanted to do that I just didn't want to change too much so you don't refuse update. I will push the PR tomorrow with collapse and hide that table at the bottom when it's not default. It's a one liner :)

**Pull request merged**
