### PR TITLE
Add generic support for links to scripts from syslog messages

### PR DESCRIPTION
**Pull request by VanWeapon**
Follow up to #332, 

I'm still not very well versed in native DOM traversal/manipulation to replace the jQuery method, if you have advice on that I'll happily re-write those two jQuery functions to use native. 

Test results from running in console:

image

### CODE REVIEW

**Comment by VanWeapon** [comment]
Thoughts on changing 
 `jQuery("td.vt:contains('-------- STACK TRACE ---------')").each(function (`

to simply this?
`jQuery("td.vt')").each(function (`

Running in console for 100 rows took 120ms, but then it doesn't become dependant on specific key words being in the table cell for it to try and find links to generate. People could structure custom log messages with any of the 3 syntaxes if they don't want to/can't use `NiceError` or stack traces, and let SNUtils still add links for them.

**Comment by arnoudkooi** [comment]
Thanks, I do see some "false positives"

Google Chrome20221207 - 1400

And should maybe open the links in a new tab (target _blank)
Another thing I see is that it not applies when browsing through pages via the list navigator arrows.

Thoughts?

**Comment by VanWeapon** [comment]
Yeah I noticed the false positives as well, although i'm not sure what could be done with these unless the table names are also somehow validated before adding the link? I found there's a client side class `Table` where you can retrieve certain info about tables, but this calls GlideAjax under the hood so would be really bad for performance. 

In terms of refreshing when moving through the list, I guess the function `snuAddErrorLogScriptLinks` just needs to be called again when navigating.

Is there some event listeners you can add to those navigator arrows to re-trigger those functions?

**Comment by arnoudkooi** [comment]
I'll have a look, maybe only convert if the supposed table name starts with sys_

**Comment by VanWeapon** [comment]
Personally I'd rather leave it open to any table, that way you can make links to arbitrary tables like incident or custom tables

**Comment by arnoudkooi** [comment]
Mad a few adjustments in the last commit

**Pull request merged**
