### PR TITLE
Fix: issue in the snuDoubleClickToShowFieldOrReload function

### PR DESCRIPTION
**Pull request by ovarn**
The issue is described here: #167.

### CODE REVIEW

**Comment by arnoudkooi** [comment]
Could you add some comments to understand the magic?
Keep in mind I try to gradually remove jQuery.

**Comment by ovarn** [comment]
Of course, I will redo it :)

**Comment by ovarn** [comment]
Please, review changes.

**Comment by ovarn** [comment]
Btw, do you know why there is that condition in the script?
`event.target.parentElement.classList.contains('label-text')`
I was not able to find a case where it's needed. Fast testing without that sub-condition did not break anything. But I decided not to remove it. Maybe you can remember? I see that it was added here:
https://github.com/arnoudkooi/ServiceNow-Utils/commit/e8f325943ab8e17c6641c095faf8a4415ff54e54

**Comment by arnoudkooi** [comment]
> Btw, do you know why there is that condition in the script? `event.target.parentElement.classList.contains('label-text')` I

Not sure. I believe it is used in some cases where Technical Names is applied. where I'm changing the original label, move the hyperlink etc.
Please don't remove this type of condition :)

**Pull request merged**
