### PR TITLE
xml/xmlsrc slashcommands small fix

### PR DESCRIPTION
**Pull request by wiiaboo**

### CODE REVIEW

**Comment by arnoudkooi** [comment]
Thanks, will be part of a next update.
(are you aware of the latest slashcommands? check: https://twitter.com/sn_utils)

**Comment by wiiaboo** [comment]
Hadn't seen the newest ones, or even most of them, but I'll go through most of them this weekend. I'll be preparing a knowledge session on SN-utils for my colleagues for next week.

I'll start with the twitter posts then, thanks 👍

**Comment by wiiaboo** [comment]
I've been using /si, /p and /code almost daily since I've noticed them.

**Comment by arnoudkooi** [comment]
Cool, the ones like /si and /p everyone can create an personalize, but you should come accross that if you go through the twitterfeed and YouTube video. :)

**Comment by arnoudkooi** [comment]
> I'll be preparing a knowledge session on SN-utils for my colleagues for next week.

Let me know if you need help, and say hello to the NL team if they join as well :)

**Pull request merged**
